server:
  port: 80
  servlet:
    context-path: /rsgl

spring:
  application:
    name: rsgl

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  resources:
    static-locations: "classpath:/templates/"

  devtools:
    restart:
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #修改不重启的目录
      exclude: templates/**, upload/**

  jpa:
    database: oracle
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.202:1521:orcl
    username: rsgl
    password: rsgl123

#日志

#自定义属性
custom-props:
  access-ignore: include,webjars,login,doLogin,main/
  tysq-path: http://192.168.0.201/tysq/tysqRestWS/callService.do
  app-code: RSGL
